---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "demo"
  namespace: "default"
  labels:
    app: "demo"
spec:
  replicas: 1 # tells deployment to run 1 pods matching the template
  selector:
    matchLabels:
      app: "demo"
  template:
    metadata:
      labels:
        app: "demo"
        version: BUILD_VERSION
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: credentials
      containers:
      - name: "github-agnnn-models"
        image: MODEL_IMAGE_NAME
        volumeMounts:
        - name: google-cloud-key
          mountPath: "/tmp/credentials"
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /tmp/credentials/sa.json
---
apiVersion: v1
kind: "Service"
metadata:
  name: "demo"
  labels:
    app: "demo"
  namespace: "default"
spec:
  type: "LoadBalancer"
  sessionAffinity: "None"
  externalTrafficPolicy: "Cluster"
  ports:
  - port: 80
    targetPort: 80
    protocol: "TCP"
  selector:
    app: "demo"
    version: BUILD_VERSION
status:
  loadBalancer: {}
